### ISSUE TITLE
`\p{…}` and `\P{…}`

### ISSUE THREAD

**Issue by mathiasbynens** [mathiasbynens/es-unicode-regexp-proposal#2]
See Unicode TR #18: http://unicode.org/reports/tr18/#Categories

---

What Perl does: ~~http://docs.activestate.com/activeperl/5.10/lib/pods/perlunicode.html#unicode_character_properties~~
http://perldoc.perl.org/perlunicode.html#Unicode-Character-Properties

Note that JS would probably need to support `\p{Cs}` as well.

> For backward compatibility (with Perl 5.6), all properties mentioned so far may have `Is` prepended to their name, so `\P{IsLu}`, for example, is equal to `\P{Lu}`.

XRegExp does the same, so it could be nice to support the `Is` prefix natively as well.

Generally I’d prefer to be strict and only support One True Way of doing things, though. For that reason I’d rather not support the aliases in `PropertyAlias.txt` and `PropertyValueAlias.txt` either.

**Comment by mathiasbynens** [comment]
Some more ideas: https://bugzilla.mozilla.org/show_bug.cgi?id=258974#c17

**Comment by mathiasbynens** [comment]
cc @claudepache

**Comment by slevithan** [comment]
> XRegExp does the same, so it would probably be nice to support the Is prefix natively as well.

XRegExp intentionally does *not* support "Is" prefixes for anything (scripts, general categories, etc.) That's because "Is" doesn't add value apart from backward compatibility, yet causes confusion and incompatibility.

Some regex flavors use "Is" for scripts, some for blocks, some for scripts and blocks, some for neither. Since some script and block names collide, this causes problems, especially when porting regexes across flavors.

XRegExp uses and requires the "In" prefix for blocks, does not use any other prefixes, and does not allow "In" with non-blocks. "In" for blocks not only avoids collisions, IMO it's also very helpful to be able to know at a glance that a particular name refers to a block, due to the nature of blocks (which are not as precise as scripts, categories, etc.) AFAIK, no regex flavors use "In" for anything but blocks, which again helps make this portable.

**Comment by patch** [comment]
The latest development release of Perl v5.23.3 (2015-09-21) just added this text to the section on [Unicode blocks](https://metacpan.org/pod/release/PCM/perl-5.23.3/pod/perlunicode.pod#Blocks):

>  Our advice used to be to use the `In_` prefix as a single form way of specifying a block. But Unicode 8.0 added properties whose names begin with `In`, and it's now clear that it's only luck that's so far prevented a conflict. Using `In` is only marginally less typing than `Blk:`, and the latter's meaning is clearer anyway, and guaranteed to never conflict. So don't take chances. Use `\p{Blk=foo}` for new code. And be sure that block is what you really really want to do. In most cases scripts are what you want instead.

**Comment by slevithan** [comment]
Interesting! Just went and looked up the block and script names from Unicode 8.0.0 that start with "In". They are "Inscriptional Pahlavi" and "Inscriptional Parthian". There's also the "Inherited" script. So you can use e.g. `\p{InInscriptionalPahlavi}` for the block and `\p{InscriptionalPahlavi}` for the script.

(This isn't a problem at all in XRegExp at least since it *requires* an "In" prefix for blocks and does not allow an "In" prefix for scripts.)

**Comment by patch** [comment]
> So you can use e.g. `\p{InInscriptionalPahlavi}` for the block and `\p{InscriptionalPahlavi}` for the script.

Those currently work in Perl as well. The problem isn’t that there are any existing conflicts using the `In` prefix, but that it isn’t standardized in [UTS #18](http://unicode.org/reports/tr18/) and nothing guarantees that there won’t be conflicts in the future. For example, if we have a `Foo` block and a corresponding `\p{InFoo}`, it could conflict in the future with any added `Script` value, `General_Category` value, or binary property name of `Infoo`, `Inf Oo`, etc. Alternately, if we have an `Inbar` script, gc, or binary property and a corresponding `\p{Inbar}`, it could conflict in the future with an added `Bar` block. Fortunately UTS #18 provides a solution that is guaranteed to not conflict, using `\p{`*Property*`=`*Value*`}`: `\p{Block=Foo}`, or `\p{blk=Foo}` if the standard abbreviations are supported. The regex engines I know that currently support this syntax are [Perl](http://perldoc.perl.org/perluniprops.html) 5.12+ (April 2010), [Java](http://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html) 7+ (July 2011), [ICU4C](http://userguide.icu-project.org/strings/regexp), and the PyPI [regex](https://pypi.python.org/pypi/regex) module.

Here are the current `In*` properties and gc/script/block values:
* `Indic_Positional_Category` (`InPC`) property
* `Indic_Syllabic_Category` (`InSC`) property
* `Initial_Punctuation` (`Pi`) value of the `General_Category` (`gc`) property
* `Inherited` (`Zinh`) value of the `Script` (`sc`) property
* `Inscriptional_Pahlavi` (`Phli`) value of the `Script` (`sc`) property
* `Inscriptional_Parthian` (`Prti`) value of the `Script` (`sc`) property
* `Inscriptional_Pahlavi` value of the `Block` (`blk`)
* `Inscriptional_Parthian` value of the `Block` (`blk`)

Looking at those and what’s bound to be added to Unicode as it expands, as well as the increasing complexity added to regex engines that continue to implement UTS #18, I think the `In` and `Is` prefixes add confusion since there’s no clear delineation to the property names/values. Additionally, matching against the `Block` property has very little use since blocks are just arbitrary implementation details of Unicode, as opposed to the `Script` and `Script_Extension` properties which have much value in natural language processing. I work in internationalization and multilingual search, and the properties I use most frequently are `General_Category` and `Script_Extension`, but never `Block`.

Note that UTS #18 [§1.2 Properties](http://unicode.org/reports/tr18/#Categories) states:
> There are both abbreviated names and longer, more descriptive names. It is strongly recommended that both names be recognized, and that loose matching of property names be used, whereby the case distinctions, whitespace, hyphens, and underbar are ignored.

If I were implementing a new regex engine (or adding new `\p` support to an existing one), I would forgo the `Is` and `In` prefixes entirely; instead supporting the following:
* `\p{`*Property*`=`*Value*`}`
* `\p{`*General Category Value*`}`
* `\p{`*Binary Property*`}`
* `\p{`[*Compatibility Property*](http://unicode.org/reports/tr18/#Compatibility_Properties)`}`
* the negated forms (`\P`) and standard abbreviations of the above
* `\N{`*Character Name*`}`
* `\N{`*Sequence Name*`}`

Note that I intentionally left out `\p{`*Script Value*`}` because `Script_Extension` (`scx`) is more important than `Script` (`sc`) and I would’t give Script its own shortcut, instead using `\p{sc=Script}` or `\p{scx=Script}` as desired.

`\p{`*Property*`=`*Value*`}` is the most important building block for full access to Unicode properties and the rest are just syntactic sugar. It’s easier to add new features and syntax in the future than it is to remove it.

**Comment by slevithan** [comment]
> Those currently work in Perl as well.

Yes, and I realize the prefix conventions would break if future versions of Unicode added e.g. a block named "Herited", but I don't see this as likely to ever occur and pose problems in practice. But there's no reason for me to defend this usage... You've clearly stated why it's better to idea to avoid any potential for future problems by foregoing `Is` and `In` prefixes entirely in a regex engine where `\p` support is new.

Great list of Unicode features to pursue for ES. However, I find it curious that you'd include the compatibility properties in a *new* regex engine. Apart from `\X` (which I'm not sure why is in that list), they seem to mostly just add confusion and redundancy. Do you find them valuable for reasons other than that they're recommended in UTS \#18?

**Comment by patch** [comment]
> I find it curious that you'd include the compatibility properties in a *new* regex engine. […] they seem to mostly just add confusion and redundancy.

That’s a good point. I think I’m just so used to seeing them in most regex engines that I use, whereas `Is` and `In` have mixed and incompatible support.

Even as a Perl programmer (among other languages) where the mantra is *there’s more than one way to do it*, I find that Unicode regexes have one too many ways to do it. Perhaps the route to go is to evaluate the compatibility properties on a case-by-case basis. When it’s yet another alias for an existing property, there’s not much value in adding more complexity and more to document. I find `\p{graph}` and `\p{print}` to be occasionally useful shortcuts that are much more memorable than their equivalent character classes. The one compatibility property that would be particularly important for the current state of ES is `\p{word}` due to the fact that proper Unicode `\w` isn’t available in `u` mode.

**Comment by mathiasbynens** [comment]
CCing @goyakim as per https://github.com/tc39/ecma262/pull/516#issuecomment-206554769.

**Comment by mathiasbynens** [comment]
If possible, we should support only `Script_Extensions`, and not `Script`.

**Comment by mathiasbynens** [comment]
I’ve asked to update UAX44-LM3 to make supporting the `is` prefix optional for new implementations. http://unicode.org/mail-arch/unicode-ml/y2016-m06/0003.html ([thread](http://www.unicode.org/mail-arch/unicode-ml/y2016-m06/thread.html#3))

**Comment by mathiasbynens** [comment]
Some updates:

1. In order to get a better grasp of the edge cases (including everything @patch and @slevithan discussed here) I’ve added support for `\p{…}` and `\P{…}` to [regexpu](https://github.com/mathiasbynens/regexpu) (transpiler).
    - [Online demo that transpiles as you type](https://mothereff.in/regexpu#input=const+regex+%3D+/%5Cp%7BScript_Extensions%3DGreek%7D/u%3B%0Aconsole.log(%0A++regex.test(%27%CF%80%27)%0A)%3B&unicodePropertyEscape=1)
    - [Full list of supported properties/values](https://github.com/mathiasbynens/regexpu-core/blob/master/property-escapes.md)
2. I’ve started work on a spec proposal based on what I consider to be the minimum viable implementation: https://github.com/mathiasbynens/ecma262/pull/1 (Note that spec text is not a requirement for [the first few stages of an ECMAScript proposal](https://tc39.github.io/process-document/).)

**Comment by patch** [comment]
In regards to the `is` prefix: not even Perl, which probably supports the most different ways to write the same regex, allows this prefix for property values when the property name is provided.

```
$ perl -Mutf8 -E 'say "π" =~ /\p{Script=Greek}/'
1
$ perl -Mutf8 -E 'say "π" =~ /\p{Script=isGreek}/'
Can't find Unicode property definition "Script=isGreek" at -e line 1.
$ perl -Mutf8 -E 'say "π" =~ /\p{Script=Is_Greek}/'
Can't find Unicode property definition "Script=Is_Greek" at -e line 1.
```

Although Perl does support the `is` prefix for property names and standalone property values, I wouldn’t advocate for new regex engines to support this as well (and I’d probably advocate against it!).

```
$ perl -Mutf8 -E 'say "π" =~ /\p{IsScript=Greek}/'
1
$ perl -Mutf8 -E 'say "π" =~ /\p{IsGreek}/'
1
```

Perl’s specific rules are documented in [perluniprops](http://perldoc.perl.org/perluniprops.html) as `\p{Is_*}` simply being a synonym for `\p{*}` which explains the above functionality. Based on my past research, I suspect that there _might_ not be any regex engine that actually supports syntax like `Script=IsGreek`!

**Comment by mathiasbynens** [comment]
This seems to be a case of reality not matching the spec. The sensible way forward is for the spec to be updated, but it seems [that proposal](https://github.com/mathiasbynens/es-unicode-regexp-proposal/issues/2#issuecomment-223892706) is being met with some resistance.

**Comment by mathiasbynens** [comment]
Thanks for all the help, everyone!

This proposal now has its own repository: https://github.com/mathiasbynens/es-regex-unicode-property-escapes Let’s continue any discussion over there.
